### ISSUE TITLE
Accelerators does not work after automatic login

### ISSUE THREAD

**Issue by gabdub** [ubuntu-mate/mate-dock-applet#114]
I installed UM17.10 in a VM and set automatic login during installation.
Accelerators like "Super+1" worked fine at first, but after restarting they stopped working.

I found that if I closed the session and logged in again, the accelerators worked as expected.

After editing lightdm.conf and removing the automatic login, everything works fine.

```
sudo nano /etc/lightdm/lightdm.conf
[Seat:*]  
greeter-session=lightdm-gtk-greeter  
user-session=mate
autologin-user=username <<<<<< accelerators work after removing this line

```
Mate Dock App V0.79 (GTK3)

**Comment by flexiondotorg** [comment]
@gabdub Thanks for reporting this issue. Can you confirm if this is still a problem in Ubuntu MATE 19.04?

**Comment by gabdub** [comment]
It seems that now works well, at least on my home PC (UM19.04).
Tomorrow I'll try reinstalling UM19.04 in a VM and choose automatic login to see if it is an installation issue or if the issue is completely solved now.

**Comment by gabdub** [comment]
I repeated all the steps and now it is working well.
This was probably a problem with the automatic login and not with the dock.
