### ISSUE TITLE
pinned app is showing twice in the panel

### ISSUE THREAD

**Issue by pepo-k** [ubuntu-mate/mate-dock-applet#200]
Hello,
my setup in ~/.config/mate_dock_applet.conf is as follows:
`<?xml version='1.0' encoding='us-ascii'?>
<root><pinned_apps><desktop_file name="firefox.desktop" /><desktop_file name="doublecmd.desktop" /><desktop_file name="palemoon.desktop" /><desktop_file name="mozo-made.desktop" /></pinned_apps><ind_type light="0" /><show_all show_all="True" /><multi_ind show_multi="False" /><use_win_list uwl="True" /><win_from_cur_ws_only wcw="False" /><panel_change_color pcc="False" /><dock_panel_change_only dcc="False" /><panel_act_list pal="True" /><bg_type type="0" /><fallback_bar_col><col value="128" /><col value="128" /><col value="128" /></fallback_bar_col><spacing spc="1" /><attention_type type="1" /><popup_delay delay="400" /><saved_configs /><pinned_apps_all_workspaces paoaws="True" /><dock_fixed_size dfs="-1" /><click_action ca="0" /><theme id="0" /></root>`
I have pinned palemoon - the upper icon.
When I click on launcher icon to start palemoon, a new icon appears for the running palemoon - the below icon. See screenshot!
When I click 2nd time on the upper icon a 2nd instance of palemoon starts.
![Screenshot at 2020-09-20 00-07-36](https://user-images.githubusercontent.com/71571227/93690266-ae27a300-fad6-11ea-9ff6-ff692a671fe6.png)
On Firefox it does not create a 2nd icon, it uses the launcher icon, as it should be.
How to set it the same way on palemoon? I do not want the palemoon icon twice there.

**Comment by pepo-k** [comment]
now I have another strange behaviour ...
When I click on palemoon launcher to start it ...
Then I still get 2nd icon, but now not a palemoon icon is used, but some strange gears icon. Is totally confusing!
![Screenshot at 2020-09-21 21-23-54](https://user-images.githubusercontent.com/71571227/93811976-45b10100-fc51-11ea-94ac-2fcb59e6d6ed.png)

**Comment by pepo-k** [comment]
now I have another strange behaviour ...
When I click on palemoon launcher to start it ...
Then I still get 2nd icon, but now not a palemoon icon is used, but some strange gears icon. Is totally confusing
![Screenshot at 2020-09-21 21-23-54](https://user-images.githubusercontent.com/71571227/93811976-45b10100-fc51-11ea-94ac-2fcb59e6d6ed.png)

**Comment by pepo-k** [comment]
this project seems to be down, is there no admin or author?

**Comment by JSBern** [comment]
does this happen with any other app than pale moon

**Comment by pepo-k** [comment]
some app was also doing this, but sorry I cannot remember what was it ...

**Comment by pepo-k** [comment]
so is there any workaround?!
can I somehow help with any debugging?

**Comment by JSBern** [comment]
I'll look into it but it may be a little while

**Comment by JSBern** [comment]
Also does it show couple if launched from the application menu

**Comment by JSBern** [comment]
Double not couple

**Comment by pepo-k** [comment]
- this is when launching over advanced mate menu 

![Screenshot at 2020-11-05 23-46-46](https://user-images.githubusercontent.com/71571227/98305033-5fb86000-1fc1-11eb-934d-8cbeee33f3ff.png)

**Comment by pepo-k** [comment]
- and the same is also when running over Alt+F2 (aplication run) shortcut

**Comment by pepo-k** [comment]
Should I provide any config files sticked with this problem?

**Comment by pepo-k** [comment]
May I ask, is there any progress?

**Comment by JSBern** [comment]
Can you run palemoon from the terminal and see if it gives any errors or even any output at all would be helpful

**Comment by pepo-k** [comment]
i put into terminal: 
$ palemoon 

palemoon was started, icon in panel is still strange, so no change against the standard clicking on launcher in panel

as output in terminal : 

autosizer-bs: bootstrap.js loaded.
autosizer-bs: Importing Autosizer.
autosizer-bs: Autosizer imported.
*************************
A coding exception was thrown in a Promise resolution callback.
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full message: TypeError: window.gBrowser.ownerDocument.watch is not a function
Full stack: onLoad@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/doma/.moonchild%20productions/pale%20moon/pvb4sm24.default/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/bootstrap.js -> jar:file:///home/doma/.moonchild%20productions/pale%20moon/pvb4sm24.default/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/packages/browserWindowOverlay.js:700:5
onLoadDelayed@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/doma/.moonchild%20productions/pale%20moon/pvb4sm24.default/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/bootstrap.js -> jar:file:///home/doma/.moonchild%20productions/pale%20moon/pvb4sm24.default/extensions/%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D.xpi!/packages/browserWindowOverlay.js:600:4
process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:932:23
walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:11

*************************

**Comment by JSBern** [comment]
it looks more like a palemoon issue maybe file a bug there?

**Comment by pepo-k** [comment]
thanks
I will try there also ...

But the issue is somehow similar happening also on libreoffice. Is still have librecalc icon as active, but beside this in the dock also additional gear icon comes up, just because of libreoffice was opened. After closing libreoffice, the libre calc icon is gone, but gear icon remains until restart of pc.

**Comment by wolfbeast** [comment]
the "coding exception" is because one of the extensions in use is using the non-standard and now removed "watch" function which was a debug-intended function. That wouldn't have any affect on what way a dock displays the program icons though, only prevent the extension from working properly.

**Comment by pepo-k** [comment]
Thanks for reply.
But sorry, for my understanding, what extension do you mean?
Extension addon in Palemoon or some extension in mate dock applet or something else?

**Comment by JSBern** [comment]
Now that I looked at the error better that does look to be the case, I did look through the code and I did not see anything obvious so someone more experienced than myself probably needs to look at it, I have noticed similar issues with the plank dock with other apps and they have yet to be fixed as far as I'm aware, one other thing you could try would be to see if it does it on other docks or plank, docky, or similar if so it's probably a palemoon issue if not it's a dock issue, also worth noting the dock will no longer be included in future Ubuntu MATE images as it's not considered up to par as of now, also as far as the extension goes yes a palemoon extension, but it's highly unlikely that the extension is causing the error as I installed palemoon with no extensions and I replicated the behavior easily. Also if LO Calc is doing the same it may be a dock issue, but unfortunately the dock is not under very active development, maybe that will change, but currently I don't have the knowledge or experience to do the work that needs done. Sorry for the long reply

**Comment by wolfbeast** [comment]
Extension added to Pale Moon.

**Comment by pepo-k** [comment]
thanks for your replies

Dear Wolf, - if it is a palemoon extension, how can I find easily which addon causes the problem? Or only one by one to disable?

Dear Bern, - you note about not including mate dock is making me sad. 
Is there a good alternative for vertical placement of the bar, at least that good like on mate dock applet?

**Comment by wolfbeast** [comment]
@JSBern It's unlikely to be a Pale Moon issue because a lot of people use Pale Moon for Linux in various docks and we haven't heard anything like this until now. Also if other completely unrelated applications display the same behaviour it's likely a dock implementation issue or perhaps some interop issue with the way the programs are structured.
That being said if there is an improvement that can be made on our side to prevent this kind of behavior then you're welcome to open an enhancement issue on [our repo](https://repo.palemoon.org/MoonchildProductions/Pale-Moon) for it and we can look into if it's feasible to implement without impacting other environments.

@pepo-k I suggest you ask on our [forum](https://forum.palemoon.org) - it'd be off-topic for this issue tracker.

**Comment by JSBern** [comment]
I haven't been able to find anything, and the apps I had issue were with the plank dock not the MATE dock applet

**Comment by pepo-k** [comment]
So, I have tried to disable all 7 addons and themes in palemoon, but I still get no progress. I always get the additional gear icon instead of using the palemoon launcher icon.

Also when I start palemoon without any addons over terminal, palemoon is starting as normal, but icon in panel is still the strange gear icon, so no change against the standard clicking on launcher in panel.
There is no additional output in terminal window - it is just empty there.

I am not able to resolve this on my own and it looks like, that there is probably nobody who can help me in this.

**Comment by pepo-k** [comment]
I have now tried the plank dock, and there is a similar behaviour of Palemoon. It is the 2nd icon from bottom.
![Screenshot at 2020-12-24 10-43-09](https://user-images.githubusercontent.com/71571227/103079956-2f5e6c80-45d5-11eb-8615-c74453323fc8.png)

When I once again start additional palemoon from menu, it creates also an real icon of palemoon, but the browser windows are collected in the one strange icon (2nd from bottom).
This is beyond my knowledge, I can not solve it by myself.

**Comment by pepo-k** [comment]
I tried the advice here:
https://forum.palemoon.org/viewtopic.php?p=200804#p200804
- and this made the trick.
Now is it working like it should.
It appears to be the problem in the installation files, in desktop file, there are either a few typos or it is not suitable enough for the mate dock applet and also not for the plank.
