### ISSUE TITLE
Add l10n

### ISSUE THREAD

**Issue by meequz** [ubuntu-mate/mate-dock-applet#43]
The applet has only English interface. I want to translate it to my native language, but it seems the applet doesn't use gettext or other mechanism for translation (and l10n and i18n). Can someone please add it?

**Comment by robint99** [comment]
This will definitely be added at some point in the future, but because I'm quite busy at the moment it may take a while....

**Comment by darkshram** [comment]
@robint99 once you get the time to do it, I want to help doing the spanish support.

**Comment by rdlf4** [comment]
> This will definitely be added at some point in the future, but because I'm quite busy at the moment it may take a while....

I know this thread is way too old, but because I didn't want to create a new one, if @robint99 would like to consider Launchpad as a viable solution, I may be able to help with translations from there.

**Comment by flexiondotorg** [comment]
Closing this issue so we can track progress via #115 :+1:
