### ISSUE TITLE
Can this be made to work with XFCE please?

### ISSUE THREAD

**Issue by eev2** [ubuntu-mate/mate-dock-applet#73]
Hi. I would like to ask, if it is not too much work, if you could please make this application work for the XFCE panel. Thank you.

**Comment by oz123** [comment]
@eev2 , 

mate desktop doesn't require much more resources than xfce... And you can copy most of the interesting functionality from this plugin to an xfce plugin. Here is a skeleton for an xfce plugin panel in Python.
It's written in Python 2, so there are subtle differences. 
https://git.xfce.org/panel-plugins/xfce4-rss-plugin/tree/panel-plugin

**Comment by robint99** [comment]
I'll take a look at this when I've got some free time. and if it won't take too much work to get the applet working on XFCE then I'll definitely do it :)

**Comment by DanielPower** [comment]
In the meantime, there's an Xfce plugin for Dockbarx, which does essentially the same thing, but also has some theming support. Unfortunately Dockbarx development is pretty much dead.

**Comment by kq01526** [comment]
> @DanielPower wrote:
> Unfortunately Dockbarx development is pretty much dead.

Not true:

https://github.com/M7S/dockbarx/issues/24#issuecomment-238443095
https://github.com/M7S/dockbarx/tree/pygi-migration

**Comment by flexiondotorg** [comment]
Thanks for showing an interest, but this applet is intended for use with MATE. Pull requests to add support are welcome but we'll not be doing that work ourselves. Sorry :hugs:
