### ISSUE TITLE
Always on top in context menu

### ISSUE THREAD

**Issue by scruball** [ubuntu-mate/mate-dock-applet#86]
Not exactly best place for a feature request, I know. Sorry for that.

Would it be possible to add "Always on top" in context menu for an app window? that would be much appreciated and would make my life much easier using Mutter for Window manager.

**Comment by flexiondotorg** [comment]
Thanks for showing an interest :smiley: This project is primarily designed for use with MATE Desktop and it's components. Sorry, but we won't be working on the feature you've suggested to integrate better with Mutter. But, we are happy to review pull requests that support other window managers and environments :+1:
